<a href="https://colab.research.google.com/github/Alishba-Jawed/SAM-AI-Tech-Task/blob/main/Movie_Genre_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
data = pd.read_excel("/content/movie genres.xlsx")

In [3]:
data

,genre,title,text
0,Drama,12 Angry Men,The defense and the prosecution have rested an...
1,Drama,One Flew Over the Cuckoo's Nest,A petty criminal fakes insanity to serve his s...
2,Drama,Hope,After 8-year-old So-won narrowly survives a br...
3,Drama,Radical,"In a Mexican border town plagued by neglect, c..."
4,Drama,American History X,Derek Vineyard is paroled after serving 3 year...
...,...,...,...
1169,Horror,Texas Chainsaw Massacre,"After nearly 50 years of hiding, Leatherface r..."
1170,Comedy,Hot Tub Time Machine 2,After their first adventure with the Hot Tub T...
1171,Comedy,Vive la France,Muzafar and Feruz are two easy going shepherds...
1172,Drama,Cuties,"Amy, an 11-year-old girl, joins a group of dan..."
1173,Horror,Ouija,A group of friends must confront their most te...

In [4]:
data.isnull().sum()

genre    0
title    0
text     0
dtype: int64

In [5]:
data.dtypes

genre    object
title    object
text     object
dtype: object

**GENDER COLUMN**

In [6]:
data["genre"].mode()

0    Drama
Name: genre, dtype: object

In [7]:
data["genre"] = data["genre"].fillna(data["genre"].mode()[0]) #Filling Null Value in genre column

**TEXT COLUMN**

In [8]:
data["text"].mode()

0    "Loro", in two parts, is a period movie that c...
Name: text, dtype: object

In [9]:
data["text"] = data["text"].fillna(data["text"].mode()[0]) #Filling Null Value in text column

**VERFY DATA IS CLEAN**

In [10]:
data.isnull().sum()

genre    0
title    0
text     0
dtype: int64

In [11]:
data["genre"] = data["genre"].str.split(", ").str[0]
print(data["genre"].nunique())

3

In [12]:
X = data["text"] #Features

In [13]:
y = data["genre"] #Target

In [14]:
X

0       The defense and the prosecution have rested an...
1       A petty criminal fakes insanity to serve his s...
2       After 8-year-old So-won narrowly survives a br...
3       In a Mexican border town plagued by neglect, c...
4       Derek Vineyard is paroled after serving 3 year...
                              ...
1169    After nearly 50 years of hiding, Leatherface r...
1170    After their first adventure with the Hot Tub T...
1171    Muzafar and Feruz are two easy going shepherds...
1172    Amy, an 11-year-old girl, joins a group of dan...
1173    A group of friends must confront their most te...
Name: text, Length: 1174, dtype: object

In [15]:
y

0        Drama
1        Drama
2        Drama
3        Drama
4        Drama
         ...
1169    Horror
1170    Comedy
1171    Comedy
1172     Drama
1173    Horror
Name: genre, Length: 1174, dtype: object

In [16]:
print(len(X))

1174

In [17]:
print(len(y))

1174

In [18]:
import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z\s]', '', text)  # Remove punctuation & numbers
    text = re.sub(r'\s+', ' ', text).strip() # Remove extra spaces
    return text

data['text'] = data['text'].apply(clean_text)

Encoding Target

In [19]:
from sklearn.preprocessing import LabelEncoder

In [20]:
le = LabelEncoder()
y = le.fit_transform(y)

Training

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
X_train , X_test, y_train, y_test = train_test_split(
    X,y,test_size=0.30, random_state=42
)

Categorical to Numerical by TF-IDF

In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [24]:
vectorizer = TfidfVectorizer(
    stop_words='english',
    max_features=50000
)

In [25]:
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec =  vectorizer.transform(X_test)

**NAIVE BAYES**

In [26]:
from sklearn.naive_bayes import MultinomialNB

In [27]:
nb = MultinomialNB()

In [28]:
X_train = X_train.squeeze()
X_test = X_test.squeeze()

In [29]:
print(X_train.shape)
print(X_test.shape)

(821,)
(353,)

In [30]:
print(X_train_vec.shape)
print(X_test_vec.shape)

(821, 7531)
(353, 7531)

In [31]:
nb.fit(X_train_vec, y_train)

MultinomialNB()

In [32]:
y_pred = nb.predict(X_test_vec)

**Evaluation**

In [33]:
from sklearn.metrics import accuracy_score

In [34]:
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.6543909348441926

In [35]:
from sklearn.metrics import confusion_matrix

In [36]:
print(confusion_matrix(y_test, y_pred))

[[ 94  61   0]
 [ 22 137   0]
 [ 14  25   0]]

**SVM**

In [37]:
from sklearn.svm import LinearSVC

In [38]:
svm = LinearSVC()

In [39]:
svm.fit(X_train_vec, y_train)

LinearSVC()

In [40]:
y_pred = svm.predict(X_test_vec)

**Evaluation**

In [41]:
accuracy_score(y_test, y_pred)

0.6685552407932012

In [42]:
print(confusion_matrix(y_test, y_pred))

[[106  49   0]
 [ 39 119   1]
 [ 11  17  11]]