<a href="https://colab.research.google.com/github/Alishba-Jawed/SAM-AI-Tech-Task/blob/main/Spam_SMS_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv("/content/spam.csv", encoding = "Latin-1")

In [ ]:
data

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

In [ ]:
time_counts = data["v1"].value_counts()
time_counts.values

array([4825,  747])

In [ ]:
data = data[["v1", "v2"]]

In [ ]:
data.columns= ["Labels","Messages"]

In [ ]:
data["Labels"].unique()

array(['ham', 'spam'], dtype=object)

Categorical to Numerical by Mapping

In [ ]:
data = data.copy()# Warning means Pandas is unsure if you're modifying original data or a copy (.copy() to avoid it)
data["Labels"] = data["Labels"].map({"spam" : 1, "ham" : 0})

Splitting For Training

In [ ]:
X = data[["Messages"]]

In [ ]:
y = data["Labels"]

In [ ]:
X

                                               Messages
0     Go until jurong point, crazy.. Available only ...
1                         Ok lar... Joking wif u oni...
2     Free entry in 2 a wkly comp to win FA Cup fina...
3     U dun say so early hor... U c already then say...
4     Nah I don't think he goes to usf, he lives aro...
...                                                 ...
5567  This is the 2nd time we have tried 2 contact u...
5568              Will Ì_ b going to esplanade fr home?
5569  Pity, * was in mood for that. So...any other s...
5570  The guy did some bitching but I acted like i'd...
5571                         Rofl. Its true to its name

[5572 rows x 1 columns]

In [ ]:
y

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: Labels, Length: 5572, dtype: int64

Training

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    data["Messages"], data["Labels"],  test_size= 0.30, random_state = 42)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
model = LogisticRegression()

Categorical to Numerical Using TF-IDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
vectorizer = TfidfVectorizer()

In [ ]:
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

In [ ]:
model.fit(X_train_vec, y_train)

LogisticRegression()

Testing

In [ ]:
y_train_predict = model.predict(X_train_vec)
y_test_predict = model.predict(X_test_vec)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
Training_Accuracy = accuracy_score(y_train, y_train_predict)
Training_Accuracy

0.9741025641025641

In [ ]:
Testing_Accuracy = accuracy_score(y_test_predict, y_test)
Testing_Accuracy

0.9659090909090909

In [ ]:
print(f"Training accuracy : {Training_Accuracy}\nTest accuracy : {Testing_Accuracy}")

Training accuracy : 0.9741025641025641
Test accuracy : 0.9659090909090909

**Now Veriify:**

In [ ]:
message = ["Win a free lottery now"]

In [ ]:
messages_vec = vectorizer.transform(message)
prediction = model.predict(messages_vec)

In [ ]:
print("SPAM" if prediction [0] == 1 else "HAM")

SPAM